<?php return [
    [
        'id'    => 'bibendum-parturient-laoreet',
        'title' => 'Bibendum parturient laoreet ',
        'icon'  => null,
        'depth' => 2,
        'smart' => null,
    ],
    [
        'id'    => 'nec-neque-sollicitudin',
        'title' => 'Nec neque sollicitudin ',
        'icon'  => null,
        'depth' => 2,
        'smart' => null,
    ],
    [
        'id'    => 'inceptos-ut-blandit-risus-diam',
        'title' => 'Inceptos ut blandit risus diam',
        'icon'  => null,
        'depth' => 2,
        'smart' => null,
    ],
    [
        'id'    => 'magna-inceptos-pede-tempus',
        'title' => 'Magna inceptos pede tempus',
        'icon'  => null,
        'depth' => 3,
        'smart' => null,
    ],
    [
        'id'    => 'habitasse-aliquet-cursus-eni-nascetur',
        'title' => 'Habitasse aliquet cursus eni nascetur ',
        'icon'  => null,
        'depth' => 2,
        'smart' => null,
    ],
    [
        'id'    => 'lectus-fusce-posuere-erat',
        'title' => 'Lectus fusce posuere erat ',
        'icon'  => null,
        'depth' => 3,
        'smart' => null,
    ],
    [
        'id'    => 'aliquet-potenti-dictum-rutrum',
        'title' => 'Aliquet potenti dictum rutrum ',
        'icon'  => null,
        'depth' => 3,
        'smart' => null,
    ],
    [
        'id'    => 'aliquet-taciti-per-nascetur-risus',
        'title' => 'Aliquet taciti per nascetur risus ',
        'icon'  => null,
        'depth' => 2,
        'smart' => null,
    ],
    [
        'id'    => 'cum-tortor-montes-per-ornare',
        'title' => 'Cum tortor montes per ornare',
        'icon'  => null,
        'depth' => 3,
        'smart' => null,
    ],
    [
        'id'    => 'nunc-tortor-hymenaeos',
        'title' => 'Nunc tortor hymenaeos ',
        'icon'  => null,
        'depth' => 2,
        'smart' => null,
    ],
];
